# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 029bfb126fa3ab78f3f73fd2313799891ba052b2f8e7d8868a27884ec63a3dbb15e1d4a8798fc7f3b851e2c888c661fff0a573be7b7a9c6b862a6345ad918b8d

test:
  secret_key_base: 872f474418d3871295573e2da4138eb8595a585ba5f6a688fe5106c9934aabdc043f9ebc1a088e4b171d0cf73876d29e0525762d900af62924f13879644fca26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
